### ISSUE TITLE
Suggestion: "Edit this page" link

### ISSUE THREAD

**Issue by SeanKilleen** [dennisdoomen/blog#1]
I've gotten some great edits in the form of PRs from people who are confused. It also really helps when content is migrated from elsewhere too. People fix image links, page links, etc. It's really nice!

**Comment by dennisdoomen** [comment]
![image](https://user-images.githubusercontent.com/572734/37755508-0b82620c-2da6-11e8-94d5-786173d3008f.png)

This is awesome ;-)
