### ISSUE TITLE
Setup SSL for the new site

### ISSUE THREAD

**Issue by dennisdoomen** [dennisdoomen/blog#15]

**Comment by SeanKilleen** [comment]
I recommend CloudFlare for this, and use it on my own GitHub pages site. Here's a post I wrote up that might help: https://seankilleen.com/2016/12/now-running-on-cloudflare/

**Comment by dennisdoomen** [comment]
Do I need to add the CNAME record to the repo before I start fiddling around with Cloudfare?

**Comment by SeanKilleen** [comment]
You'll need to point your DNS registrar to Cloudflare's nameservers, and then add the appropriate records to point cloudflare to github. 

I don't think adding the CNAME now will matter (e.g. I don't think it'll stop `dennisdoomen.github.io` from working), but I'm not 100% sure.

**Comment by dennisdoomen** [comment]
Thanks for that post. I think I've set up everything correctly. I'll just have to wait for the SSL certificate to become available

**Comment by dennisdoomen** [comment]
It's working now.
