### ISSUE TITLE
Convert pages to Markdown? 

### ISSUE THREAD

**Issue by SeanKilleen** [dennisdoomen/blog#23]
I noticed that the `_posts` are all html at this point and I couldn't remember: do you plan to convert them to markdown? Would likely go a long way to making them easier to edit, and fix some of the formatting, particularly on things like code snippets.

**Comment by dennisdoomen** [comment]
I didn't even notice that. I may do that retroactively whenever I think I need to update something. Or do you think that's a bad idea?

**Comment by SeanKilleen** [comment]
@dennisdoomen I'd recommend coming up with a prioritized list that favors:

* Your most popular posts
* Code-heavy posts
* Formatting-heavy posts

If you know the URLs that matter, you can create a checklist in a Github issue, mark it as `help wanted`, and we can convert them one at a time with PRs and then check them off.

**Comment by SeanKilleen** [comment]
I've created #28, so I'll close this. @dennisdoomen, I recommend editing that github issue and adding pages to the checklist as I've defined above. Once you do that we can start knocking them out.
