### ISSUE TITLE
Housekeeping: Ensure Google Analytics works

### ISSUE THREAD

**Issue by SeanKilleen** [dennisdoomen/blog#3]
It looks like you may have Google Analytics set up. If not, I highly recommend it.

Google analytics ends up being really instrumental especially around 404s. I have an alert set up for the title of my 404 page, and then I look at what URLs people were looking for, and add redirects to them. Was hugely helpful early on.

**Comment by SeanKilleen** [comment]
I'm assuming you're up and running with the analytics here so you can probably close this assuming you're getting correct live traffic etc from the site

**Comment by dennisdoomen** [comment]
No, something is broken. I'll need to check tonight.

**Comment by dennisdoomen** [comment]
Ah, I was using the wrong Analytics code. Now it works.
