### ISSUE TITLE
Relative urls across years are broken

### ISSUE THREAD

**Issue by bartlannoeye** [dennisdoomen/blog#47]
I noticed some of the relative urls pointing to another year (hence folder) are incorrectly routed. You'll probably need some Jekyll syntax in the markdown (if it works similar like Hugo for links).

Examples: 
https://www.continuousimprover.com/2023/03/test-naming.html: "earlier post" links to https://www.continuousimprover.com/2023/03/2016/11/the-three-mental-modes-of-working-with.html (see 2023/03/2016/11)

https://www.continuousimprover.com/2022/02/gitversion.html: "guidance" links to https://www.continuousimprover.com/2022/02/2020/03/keep-source-control-history-clean.html (see 2022/02/2020/03)

**Comment by SeanKilleen** [comment]
Correct -- might want to do a pass searching for `](/` (start of a link) and then replace the applicable pieces with the jekyll syntax `{% post_url 2010-07-21-name-of-post %}`

This is probably leftover from the original conversion.

**Comment by dennisdoomen** [comment]
Thank you for reporting this @bartlannoeye. And thanks for your suggestions @SeanKilleen

**Comment by dennisdoomen** [comment]
Fixed all of them now (I hope). I didn't know `post_url` would cause the Jekyll engine to validate the links. That's quite neat.
